#\!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
run.py — cross-platform launcher: venv + deps + native GTK/pango + app.
"""
from __future__ import annotations

import hashlib
import os
import platform
import subprocess
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
VENV_DIR = BASE_DIR / ".venv"
REQUIREMENTS = BASE_DIR / "requirements.txt"
HASH_MARKER = VENV_DIR / ".deps-hash"
APP_ENTRY = BASE_DIR / "invoice_cli.py"

IS_WINDOWS = platform.system() == "Windows"


def _supports_color() -> bool:
    if not sys.stdout.isatty():
        return False
    if IS_WINDOWS:
        return os.environ.get("WT_SESSION") is not None or "ANSICON" in os.environ
    return True


def say(msg: str, code: str = "36") -> None:
    prefix = "[bootstrap]"
    if _supports_color():
        print(f"\033[{code}m{prefix}\033[0m {msg}")
    else:
        print(f"{prefix} {msg}")


def warn(msg: str) -> None:
    say(msg, code="33")


def err(msg: str) -> None:
    say(msg, code="31")


def venv_python() -> Path:
    if IS_WINDOWS:
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python"


def running_in_venv() -> bool:
    target = venv_python()
    if not target.exists():
        return False
    try:
        return Path(sys.executable).resolve().samefile(target)
    except (FileNotFoundError, OSError):
        return False


def create_venv_if_missing() -> None:
    if venv_python().exists():
        return
    say(f"Creating venv at {VENV_DIR}")
    try:
        subprocess.run([sys.executable, "-m", "venv", str(VENV_DIR)], check=True)
    except subprocess.CalledProcessError as exc:
        err(f"venv creation failed: {exc}")
        sys.exit(1)


def requirements_hash() -> str:
    if not REQUIREMENTS.exists():
        return ""
    return hashlib.sha256(REQUIREMENTS.read_bytes()).hexdigest()


def dependencies_up_to_date() -> bool:
    if not REQUIREMENTS.exists():
        return True
    if not HASH_MARKER.exists():
        return False
    try:
        return HASH_MARKER.read_text(encoding="utf-8").strip() == requirements_hash()
    except OSError:
        return False


def install_requirements() -> None:
    py = venv_python()
    say("Updating pip in venv...")
    subprocess.run([str(py), "-m", "pip", "install", "--upgrade", "pip"], check=False)
    if not REQUIREMENTS.exists():
        warn(f"No {REQUIREMENTS.name} - skipping deps install.")
        return
    say(f"Installing deps from {REQUIREMENTS.name}...")
    result = subprocess.run([str(py), "-m", "pip", "install", "-r", str(REQUIREMENTS)])
    if result.returncode != 0:
        err("Dependency install failed.")
        sys.exit(result.returncode)
    try:
        HASH_MARKER.write_text(requirements_hash(), encoding="utf-8")
    except OSError as exc:
        warn(f"Could not save hash marker: {exc}")


def ensure_native_deps() -> dict:
    try:
        sys.path.insert(0, str(BASE_DIR))
        import ensure_gtk
        return ensure_gtk.ensure()
    except Exception as exc:
        warn(f"Native deps auto-install failed: {exc}")
        warn("Set SKIP_NATIVE_DEPS=1 to skip. See README.")
        return {}


def write_sitecustomize(gtk_bin: Path) -> None:
    py = venv_python()
    try:
        result = subprocess.run(
            [str(py), "-c", "import sysconfig; print(sysconfig.get_paths()['purelib'])"],
            capture_output=True, text=True, check=True,
        )
    except subprocess.CalledProcessError as exc:
        warn(f"Cannot locate site-packages: {exc}")
        return

    site_packages = Path(result.stdout.strip())
    custom = site_packages / "sitecustomize.py"
    gtk_str = str(gtk_bin)
    content = (
        "# Auto-generated by run.py: wire up GTK DLLs for WeasyPrint.\n"
        "import os, sys\n"
        "if sys.platform == 'win32':\n"
        f"    _gtk = r{gtk_str!r}\n"
        "    if os.path.isdir(_gtk):\n"
        "        try:\n"
        "            os.add_dll_directory(_gtk)\n"
        "        except (AttributeError, OSError):\n"
        "            pass\n"
        "        if _gtk.lower() not in os.environ.get('PATH', '').lower():\n"
        "            os.environ['PATH'] = _gtk + os.pathsep + os.environ.get('PATH', '')\n"
    )
    try:
        custom.write_text(content, encoding="utf-8")
        say(f"Wrote {custom.name} - GTK DLLs will auto-load from venv.")
    except OSError as exc:
        warn(f"Could not write {custom}: {exc}")


def relaunch_in_venv(env_patch: dict) -> None:
    env_patch = env_patch or {}
    py = venv_python()
    args = [str(py), str(APP_ENTRY), *sys.argv[1:]]
    env = os.environ.copy()
    gtk_bin = env_patch.get("GTK_BIN_DIR")
    if gtk_bin:
        env["PATH"] = f"{gtk_bin}{os.pathsep}{env.get('PATH', '')}"
    say("Launching app in venv...")
    if IS_WINDOWS:
        result = subprocess.run(args, env=env)
        sys.exit(result.returncode)
    else:
        os.execve(str(py), args, env)


def main() -> None:
    if not APP_ENTRY.exists():
        err(f"App entry not found: {APP_ENTRY}")
        sys.exit(1)
    if running_in_venv():
        sys.path.insert(0, str(BASE_DIR))
        import invoice_cli
        sys.exit(invoice_cli.main())
    create_venv_if_missing()
    if dependencies_up_to_date():
        say("Python deps up to date (hash match).")
    else:
        install_requirements()
    env_patch = ensure_native_deps()
    if IS_WINDOWS and env_patch.get("GTK_BIN_DIR"):
        write_sitecustomize(Path(env_patch["GTK_BIN_DIR"]))
    relaunch_in_venv(env_patch)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted.")
        sys.exit(130)
